/**
 * ipc-handlers/configHelpers.ts — Constants and pure helpers extracted from
 * config.ts to satisfy the 300-line limit.
 */

import type { AppConfig } from '../config';

/** Config keys that can be imported/synced from external JSON files. */
export const IMPORTABLE_KEYS: (keyof AppConfig)[] = [
  'recentProjects',
  'defaultProjectRoot',
  'activeTheme',
  'activeFileIconTheme',
  'activeProductIconTheme',
  'hooksServerPort',
  'terminalFontSize',
  'terminalCursorStyle',
  'autoInstallHooks',
  'shell',
  'panelSizes',
  'windowBounds',
  'fontUI',
  'fontMono',
  'fontSizeUI',
  'keybindings',
  'showBgGradient',
  'customThemeColors',
  'terminalSessions',
  'claudeCliSettings',
  'codexCliSettings',
  'customCSS',
  'bookmarks',
  'fileTreeIgnorePatterns',
  'profiles',
  'multiRoots',
  'customPrompt',
  'promptPreset',
  'notifications',
  'agentTemplates',
  'workspaceLayouts',
  'activeLayoutName',
  'workspaceSnapshots',
  'extensionsEnabled',
  'disabledExtensions',
  'installedVsxExtensions',
  'disabledVsxExtensions',
  'lspEnabled',
  'inlineCompletionsEnabled',
  'embeddingsEnabled',
  'embeddingProvider',
  'voyageApiKey',
  'lspServers',
  'claudeAutoLaunch',
  'commandBlocksEnabled',
  'promptPattern',
  'formatOnSave',
];
