import type {
  OrchestrationAPI as MainOrchestrationAPI,
  OrchestrationEvent,
  TaskResult,
} from '@shared/types/orchestration';

export type {
  ContextBudgetConstraints,
  ContextBudgetSummary,
  ContextPacket,
  ContextPacketResult,
  ContextSelectionReason,
  ContextSnippet,
  ContextSnippetRange,
  ContextTruncationNote,
  DiagnosticsFileSummary,
  DiagnosticsSummary,
  DiffFileSummary,
  DiffSummary,
  DirtyBufferSnapshot,
  EditorSelectionRange,
  GitDiffFileSummary,
  GitDiffSummary,
  LiveIdeState,
  NextSuggestedAction,
  OmittedContextCandidate,
  OperationResult,
  OrchestrationEvent,
  OrchestrationMode,
  OrchestrationProvider,
  OrchestrationProviderProgressEvent,
  OrchestrationSessionUpdatedEvent,
  OrchestrationState,
  OrchestrationStateChangedEvent,
  OrchestrationStatus,
  OrchestrationTaskResultEvent,
  OrchestrationVerificationUpdatedEvent,
  ProviderArtifact,
  ProviderCapabilities,
  ProviderExecutionStatus,
  ProviderProgressEvent,
  ProviderSessionReference,
  RankedContextFile,
  RecentEditsSummary,
  RepoFacts,
  TaskAttemptRecord,
  TaskMutationResult,
  TaskRequest,
  TaskRequestContextSelection,
  TaskRequestMetadata,
  TaskResult,
  TaskSessionPatch,
  TaskSessionRecord,
  TaskSessionResult,
  TaskSessionsResult,
  VerificationCommandResult,
  VerificationIssue,
  VerificationProfile,
  VerificationProfileName,
  VerificationResult,
  VerificationRunStatus,
  VerificationStep,
  VerificationStepKind,
  VerificationSummary,
  WorkspaceRootFact,
} from '@shared/types/orchestration';

export interface OrchestrationAPI extends MainOrchestrationAPI {
  onTaskResult: (callback: (result: TaskResult) => void) => () => void;
  onEvent: (callback: (event: OrchestrationEvent) => void) => () => void;
}

export type {
  OrchestrationEventChannel,
  OrchestrationEventType,
  OrchestrationInvokeChannel,
} from '@shared/ipc/orchestrationChannels';
