/**
 * electron-orchestration.d.ts — Context-packet and task types re-exported from
 * @shared/types/orchestration for the ContextBuilder renderer component.
 *
 * NOTE (Wave 100 Phase F): The OrchestrationAPI interface and orchestration
 * property on ElectronAPI were removed when the chat orchestration IPC surface
 * was cut. These type re-exports remain for the live ContextBuilder component.
 * Full removal is scheduled for Phase H (Settings UI + schema narrowing).
 */

export type {
  ContextBudgetConstraints,
  ContextBudgetSummary,
  ContextPacket,
  ContextPacketResult,
  ContextSelectionReason,
  ContextSnippet,
  ContextSnippetRange,
  ContextTruncationNote,
  DiagnosticsFileSummary,
  DiagnosticsSummary,
  DiffFileSummary,
  DiffSummary,
  DirtyBufferSnapshot,
  EditorSelectionRange,
  GitDiffFileSummary,
  GitDiffSummary,
  LiveIdeState,
  NextSuggestedAction,
  OmittedContextCandidate,
  OperationResult,
  OrchestrationEvent,
  OrchestrationMode,
  OrchestrationProvider,
  OrchestrationProviderProgressEvent,
  OrchestrationSessionUpdatedEvent,
  OrchestrationState,
  OrchestrationStateChangedEvent,
  OrchestrationStatus,
  OrchestrationTaskResultEvent,
  OrchestrationVerificationUpdatedEvent,
  ProviderArtifact,
  ProviderCapabilities,
  ProviderExecutionStatus,
  ProviderProgressEvent,
  ProviderSessionReference,
  RankedContextFile,
  RecentEditsSummary,
  RepoFacts,
  TaskAttemptRecord,
  TaskMutationResult,
  TaskRequest,
  TaskRequestContextSelection,
  TaskRequestMetadata,
  TaskResult,
  TaskSessionPatch,
  TaskSessionRecord,
  TaskSessionResult,
  TaskSessionsResult,
  VerificationCommandResult,
  VerificationIssue,
  VerificationProfile,
  VerificationProfileName,
  VerificationResult,
  VerificationRunStatus,
  VerificationStep,
  VerificationStepKind,
  VerificationSummary,
  WorkspaceRootFact,
} from '@shared/types/orchestration';

